
PRIMARY_TYPES = {
    'automaker company',
    'airline company',
    'broadcasting company',
    'commercial banking company',
    'commercial bank business',
    'commercial company',
    'computer-aided engineering company',
    'company',
    'conglomerate company',
    'construction company',
    'consumer electronics company',
    'corporation',
    'energy company',
    'financial services company',
    'finance company',
    'health care company',
    'healthcare company',
    'investment company',
    'investment banking company',
    'internet company',
    'logistics company',
    'management services consulting company',
    'mining company',
    'motion picture company',
    'mobile marketing company',
    'motherboard company',
    'music industry company',
    'natural gas transmission company',
    'private equity company',
    'pharmaceutical company',
    'risk management company',
    'retail company',
    'real estate company',
    'semiconductor manufacturing company',
    'software company',
    'software engineering company',
    'specialty retailer company',
    'solar power company',
    'software development company',
    'software as a service company',
    'social network service website',
    'shoe manufacturing company',
    'telecommunications company',
    'website',
}

BACKUP_TYPES = {
    'business',
    'defense contractor business',
    'business process outsourcing company'
    'all other miscellaneous manufacturing business'
    'commercial bank business',
    'commercial organizatio',
    'organization leader',
    'organization',
    'business operation',
    'restaurant',
    'brand',
    'topic',
    'investment',
    'service',
    'fashion designer'
}
